apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Yonis-Hage/eks-project.git
    targetRevision: HEAD
    path: apps/game-2048
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

 