name: Terraform Plan

on:
    workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Checkov scan (ignore failures)
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true

      - name: TFSec scan
        uses: aquasecurity/tfsec-action@master
